# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20170329_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_graduation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_major',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_nationality',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_residency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_school',
            field=models.TextField(null=True),
        ),
    ]
