# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20170331_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_residency',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
