# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 17:05
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20170331_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_residency',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
