# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20170331_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_photo',
            field=models.ImageField(null=True, upload_to='.avatars'),
        ),
    ]
