# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_auto_20170331_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(verbose_name=django.contrib.auth.models.User)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_photo',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='admin_application',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
    ]
