# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_auto_20170403_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_application',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='admin_application',
            name='application_id',
        ),
        migrations.AddField(
            model_name='admin_application',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin_application',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='admin_application',
            name='accepted',
            field=models.NullBooleanField(),
        ),
    ]
