# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20170403_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_application',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application', unique=True),
        ),
    ]
