# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0009_auto_20170404_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_application',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='admin_application',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='application',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Admin_Application',
        ),
    ]
