# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20170404_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_photo',
            field=models.ImageField(null=True, upload_to='applications/avatars'),
        ),
    ]
