# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20170404_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_major',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
